### ISSUE TITLE
Incompatible metadata version in pyserial 3.5?

### ISSUE THREAD

**Issue by GutiCW** [pyserial/pyserial#796]
Latest version on PyPI shows `Metadata-Version: 2.0`.
But it also contains `Provides-Extra: cp2110`.
[Provides-Extra](https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use) was introduced with metadata version 2.1.

See attached "pyserial-3.5-py2.py3-none-any.whl\pyserial-3.5.dist-info\METADATA": [pyserial-3.5-py2.py3-none-any.zip](https://github.com/user-attachments/files/20329177/pyserial-3.5-py2.py3-none-any.zip).

Leads to an error when uploading to a private packaging index:
twine version 6.1.0
```python -m twine upload --verbose --skip-existing --disable-progress-bar --repository "MYPyPI" --config-file ".\.pypirc" ".downloads\pyserial\pyserial-3.5-py2.py3-none-any.whl"
INFO     Using configuration from .\.pypirc
Uploading distributions to ..._packaging/MYPyPI/pypi/upload/
ERROR    InvalidDistribution: Invalid distribution metadata: provides-extra introduced in metadata version 2.1, not 2.0`
```

When building the latest sources manually, `Metadata-Version: 2.4` is written to METADATA.
build 1.2.2.post1

**Comment by sergey-miryanov** [comment]
Try to use `twine==6.0.0` and `packaging==21.3`. It is less restrictive than latest.

**Comment by GutiCW** [comment]
> Try to use `twine==6.0.0` and `packaging==21.3`. It is less restrictive than latest.

Thanks, but that's not really an option - I don't want to downgrade the toolchain for this...
We now force to install pyserial from source distribution.

I guess there won't be any updates for pyserial (last release Nov 23, 2020). 
Does it get replaced by another package?

**Comment by sergey-miryanov** [comment]
> Does it get replaced by another package?

IDK, it is one of our dependencies.

> Thanks, but that's not really an option - I don't want to downgrade the toolchain for this...

We downgrade only one stage in our CI, because we can't update all our deps.

**Comment by kurtmckee** [comment]
@GutiCW This was fixed by #811.

@zsquareplusc @dpgeorge Please close this issue.

**Comment by dpgeorge** [comment]
@GutiCW pyserial has now been updated to use a `pyproject.toml`.  But a new release is not yet published to PyPI, so I guess your issue is not yet resolved?

**Comment by kurtmckee** [comment]
@dpgeorge It can only be resolved by a new release. I recommend closing this issue with the expectation that a new release is forthcoming. This will reduce the backlog of issues, and eliminate the administrative work later to come back and close it.

**Comment by GutiCW** [comment]
@kurtmckee, ok - thanks for taking care of this.
Any idea when the new [releae](https://github.com/pyserial/pyserial/releases) will be available on PyPI?
